### ISSUE TITLE
Dynamic Loading of terminfo module fails with Pyinstaller.

### ISSUE THREAD

**Issue by the-stanely** [Rockhopper-Technologies/jinxed#1]
in `_terminal.py` there is the following code:
```
        try:
            self.terminfo = importlib.import_module('jinxed.terminfo.%s' % term.replace('-', '_'))
        except ImportError:
            raise error('Could not find terminal %s' % term)
```
This breaks `Pyinstaller` and modules have to be imported using the `--hidden-import` option.  Because the terminal is supposed to be platform-independent, a number of modules are available in the `./jinxed/terminfo' folder.  This requires using `--hidden-import' on each of these modules.  If any new terminals are ever added, the `Pyinstaller` spec file would also need to be changed.

Because the `terminfo` folder is so small, it would be nice if  dynamic importing was not used so `Pyinstaller` would work without intervention.

**Comment by avylove** [comment]
I'm not sure it would make sense to use static imports. It's possible this list could grow and that would cause overhead on everyone. I think a long term solution would for pyinstaller ``--hidden-import`` to support wildcards.

For now, I see two options:
- You could generate the list dynamically using ``pkgutil.walk_packages()``
- If you're only building an .exe for Windows, you can probably get away with only including ``jinxed.terminfo.vtwin10`` and ``jinxed.terminfo.ansicon``. The others should be included as recursive dependencies.

**Comment by the-stanely** [comment]
Thank you for your quick reply.  I understand your concern about adding overhead to all not using pyinstaller, and agree that wildcard support for --hidden-import makes the most sense.

Maybe a note in the docs mentioning dynamic imports  not working with pyinstaller would be enough?  Not being familiar with curses or jinxed it took me a while to figure out what was failing and why.  I had to dig into the package source starting with `blessed` which eventually led me to jinxed.  Google searches for `blessed` and pyinstaller didn't turn anything up.  Programmers in a similar situation might benefit from a description of this feature.

Thanks for suggesting to include `vtwin10` and `ansicon`.  Windows is my target so knowing this will help.
