### ISSUE TITLE
new release needed for ncurses >=6.4 compatibility

### ISSUE THREAD

**Issue by M-Waszkiewicz-Anaconda** [Rockhopper-Technologies/jinxed#4]
Could you please create new release so that it is compatible with ncursers>=6.4

**Comment by avylove** [comment]
I'll try to put one out in  the next few days. If you can't wait, an easy patch should be to add ``'printf_s1'`` to ``KNOWN_FAILURES`` in ``test_tparm.py``.

**Comment by M-Waszkiewicz-Anaconda** [comment]
I can wait for couple of days, thank you!

**Comment by avylove** [comment]
Should be fixed in [1.2.1](https://github.com/Rockhopper-Technologies/jinxed/releases/tag/1.2.1)
Let me know if you run into any issues
