### ISSUE TITLE
`KERNEL32.SetConsoleMode()` raises `OSError: [WinError 87] The parameter is incorrect.`

### ISSUE THREAD

**Issue by marph91** [Rockhopper-Technologies/jinxed#5]
Hi,

a user of my app got an issue: https://github.com/marph91/jimmy/issues/9

In short:

- Windows ~10~ 11, cmd
- Traceback:
  - jimmy (packaged with pyinstaller) calls `enlighten.get_manager()` at https://github.com/marph91/jimmy/blob/e4d9bf50e2209f51d8a85719ff328d5cd0d0a0a8/src/common.py#L68
  - enlighten -> blessed -> jinxed
  - jinxed raises `OSError: [WinError 87] The parameter is incorrect.` at https://github.com/Rockhopper-Technologies/jinxed/blob/fad7d1b4a411813e4d4f1ce3e99cb685d3a4c43a/jinxed/win32.py#L181

I couldn't reproduce it on my Windows VM with cmd.

Do you have any idea how to fix it?

**Comment by avylove** [comment]
I'd guess their terminal doesn't support the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag. That's the case with older versions of Windows 10, but there is a check in that file to make sure they are using Windows 10 build number 10586 or newer. Can you ask them what version and build number they are using (Start -> Settings -> System -> About)?

**Comment by avylove** [comment]
The workaround would probably be in Jinxed to try ANSICON if the native support fails. However, it would be good to know if some condition isn't already being caught by the guard.

**Comment by marph91** [comment]
> Can you ask them what version and build number they are using (Start -> Settings -> System -> About)?

Answer from the user:

> The version of Windows I use is 11 Enterprise 23H2, build 22631.3880 and Experience Pack 1000.22700.1020.0.

So it's even windows 11. (I adapted the original post accordingly.)

**Comment by avylove** [comment]
Yeah, that's weird. We wouldn't want to fall back in that case. Best to try and figure out what's going on

**Comment by avylove** [comment]
Once I get my VM updated, I'm going to test an update to Jinxed that won't set the console mode if the needed mode is already enabled. It wasn't enabled by default before, but it looks like it is now. I don't know if that's your user's issue, but, if we don't have to set the mode, then it avoids the whole issue.

**Comment by avylove** [comment]
I released [ Jinxed 1.3.0 ](https://github.com/Rockhopper-Technologies/jinxed/releases/tag/1.3.0) with this change. Hopefully that solves the issue. If not, we can keep investigating. Either way, I think the change makes sense.

**Comment by marph91** [comment]
I guess we can close this. There was no user feedback for more than a month. If the issue isn't fixed, we can open this again.

Thanks for the support!
